export const achievementDefaults = [
 {
        id: "coffee",
        name: "Kaffe",
        description: "Tjäna poäng på att dricka kaffe!",
        currentLevel: 0,
        maxLevel: 10,
        points: 0,
        pointsPerLevel: 5,
        reward: "kaffe & kaffemärke",
        icon: "☕",
        xpReward: 10,
        hasLeveledUp: false,
    },
 {
        id: "trips",
        name: "Resor",
        description: "Tjäna poäng på att resa!",
        currentLevel: 0,
        maxLevel: 10,
        points: 0,
        pointsPerLevel: 5,
        reward: "resor & resmärke",
        icon: "🚅",
        xpReward: 10,
        hasLeveledUp: false,
    },
 {
        id: "first-trip",
        name: "Första resan",
        description: "Tjäna poäng på att resa!",
        currentLevel: 1,
        maxLevel: 1,
        points: 0,
        pointsPerLevel: 1,
        reward: "första resmärke",
        icon: "🚂",
        xpReward: 10,
        hasLeveledUp: false,
    }
]